/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":model"))
    implementation(project(":repositories"))

    // Driver JDBC (ya lo tienes)
    implementation("com.mysql:mysql-connector-j:9.3.0")

    // Jackson para leer JSON
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-core:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.15.2")
}