/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    // Internal modules
    implementation(project(":model"))
    implementation(project(":repositories"))

    // JPA and Hibernate dependencies
    implementation("jakarta.persistence:jakarta.persistence-api:3.2.0")
    implementation("org.hibernate.orm:hibernate-core:7.0.0.Final")

    // MySQL connector (version 8.4.0 is more stable than 9.x with Hibernate)
    implementation("com.mysql:mysql-connector-j:9.3.0")

    // Lombok for reducing boilerplate code (e.g. @Data, @NoArgsConstructor)
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")
}