/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":jdbc"))
    implementation(project(":jpa"))
    implementation(project(":model"))
    implementation(project(":repositories"))

    implementation("com.mysql:mysql-connector-j:9.3.0")
    implementation("com.github.freva:ascii-table:1.8.0")

}

application {
    mainClass = "cat.uvic.teknos.dam.kamika.app.App"
}