/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":jdbc"))
    implementation(project(":model"))
    implementation(project(":repositories"))
    implementation("com.mysql:mysql-connector-j:9.3.0")
    implementation("com.athaydes.rawhttp:rawhttp-core:2.6.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.0")
    implementation(project(":utilities"))

}