/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":model"))
    implementation(project(":repositories"))

    implementation("com.mysql:mysql-connector-j:9.3.0")
}